### ISSUE TITLE
Wrong/missing documentation for 'map.get.complete'

### ISSUE THREAD

**Issue by alstad** [CMAPI/cmapi#92] opened 2016-07-18 10:44 UTC
The description for `map.get.complete` is the same as for `map.message.progress` and the "Payload Properties" section is empty.

**Comment by briscoeej** [comment] 2016-08-16 22:20
Duplicate of issue #66
Now fixed.  See issue #66 for details

**Closed by briscoeej** 2016-08-16 22:20 UTC
Labels: bug
