### ISSUE TITLE
Need clarity on when to user map.error vs map.message.complete

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#98] opened 2016-09-02 17:51 UTC
4) It is not clear when to use map.error vs map.message.complete.  I believe this issue has been raised before, but the spec doesn't appear to have changed.

from message https://groups.google.com/forum/?hl=en#!topic/common-map-widget-api/rvq5Wyny9I4

**Comment by eric-briscoe** [comment] 2016-09-02 18:09
This is a duplicate of issue #94 Closing

**Closed as completed by eric-briscoe** 2016-09-02 18:09 UTC
Labels: bug
